### ISSUE TITLE
Question about Server Configuration?

### ISSUE THREAD

**Issue by bwahn** [Xorlev/gatekeeper#15]
I have 10 nginx server and In 1st nginx server, I've installed zookeeper and gatekeeper.
1) Could you explain how to update scenario of ngnix.conf which add proxy_pass,
for example, www.my.com is webpage and It would like to add foo.my.com in every 10 nodes of nginx.
2) Should I install both gatekeeper and zookeeper in the rest( 9 ea) of the nginx server?

**Comment by Xorlev** [comment]
Hi there,

Gatekeeper is most useful when you need to dynamically manage a changing list of servers in an upstream block. Do you currently use Zookeeper for service discovery?

**Comment by bwahn** [comment]
Hi, 
I could use zookeeper, and already installed it. 
I saw the upstream field in #upstream of nginx.conf.mustache.default. 
and should I configure #upstream field into zookeeper? 
Do you have a guide page or document for configuration in zookeeper?

**Comment by Xorlev** [comment]
Here's an example of using Curator discovery in an application: https://git-wip-us.apache.org/repos/asf?p=curator.git;a=blob;f=curator-examples/src/main/java/discovery/ExampleServer.java;h=96478f5fb079b2ab80d6f131a2e17d3e5c495b67;hb=HEAD
