### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by BernhardBln** [Xorlev/gatekeeper#9]
Hey,

wanted to try out this project, but neither the 1.0.0 version nor the head would compile.

For example, in the Cluster class, the other code expects methods like getClusterName or getServers, but they don't exist there. 

Also, on master, the poms of the sub-projects reference a different parent pom. 

Is there a commit that I can use to package the project?

Thanks in advance :)

Bernhard

**Comment by naksu** [comment]
I could not get building to work with the instructions on readme for 1.0.0. Cherry-pick of 8b301c6cd690ab79d8b85b46710b0242dc84b645 (manually, as there were conflicts) worked around. Not sure if that was the right thing to do.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project gatekeeper-core: Compilation failure: Compilation failure:
[ERROR] /home/vagrant/gatekeeper/gatekeeper-core/src/main/java/com/xorlev/gatekeeper/providers/discovery/AbstractClusterDiscovery.java:[21,18] error: generics are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable generics)
```

**Comment by Xorlev** [comment]
Hi @naksu,

The issue has already been corrected in master, but I'll see about releasing a 1.1.0 to signal that master is ready for use.

**Comment by naksu** [comment]
Hi Xorlev,

Thanks. I was wondering about whether it was safe to use the snapshot version.
